security:
    encoders:
          Maklarresurs\UserBundle\Entity\User: sha512

    role_hierarchy:
            ROLE_ADMIN:       ROLE_ADMIN
            ROLE_PS:          ROLE_PS
            ROLE_USER:        ROLE_USER

    providers:
            fos_userbundle:
                id: fos_user.user_provider.username

    firewalls:
            main:
                pattern: ^/
                form_login:
                    check_path: /login_check
                    login_path: /login
                    use_referer: true
                provider: fos_userbundle
                logout:       true
                anonymous:    true

    access_control:
            - { path: ^/admin/, role: ROLE_ADMIN }
            - { path: ^/supplier/, role: ROLE_PS}
            - { path: ^/user/, role: ROLE_USER}
