services:
    maklarresurs_app.main_repo:
        class: Maklarresurs\AppBundle\Repository\MainRepository
        arguments:
            - "@doctrine.orm.default_entity_manager"

    maklarresurs.login_listener:
                 class: Maklarresurs\AppBundle\EventListener\LoginListener
                 arguments:
                     - "@router"
                     - "@security.context"
                     - "@doctrine"
                 tags:
                     - {name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin}