<?php

namespace Maklarresurs\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AreaRepository extends EntityRepository
{
    public function getChildByParentIds($ids)
    {
        return count($ids) ? $this->createQueryBuilder('a')
            ->join('a.parents', 'ap')
            ->where('ap.id IN (:parentIds)')->setParameter('parentIds', $ids)
            ->getQuery()->getResult() : array()
        ;
    }
}
